# Generated by Django 4.0.6 on 2022-09-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosses',
            old_name='Age',
            new_name='BossesAge',
        ),
        migrations.RenameField(
            model_name='bosses',
            old_name='Last_name',
            new_name='BossesLast_name',
        ),
        migrations.RenameField(
            model_name='bosses',
            old_name='Name',
            new_name='BossesName',
        ),
    ]
